name: Twitter Tracker

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分鐘運行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 你需要的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests google-api-python-client # 安裝所需的庫

    - name: Run the script
      run: python twitter_tracker.py

